---
- name: Run CPU Usage check
  hosts: "{{ host_name }}"
  gather_facts: no
  vars:
    sop_notes:
      - "NOTE: Refer to CPU usage and steps as per duration [Reference: KB0012118 ]"
      - "< 1hr ( No action requried )"
      - "> 1hr ( SMS to DO alert along with top process )"
      - "> 2hr ( If utilization does not normalize, provide hourly updates of usage % to DO )"
  tasks:
    - name: Display SOP Notes
      ansible.builtin.debug:
        msg: "{{ sop_notes }}"
          
    - name: Execute top to get cpu usage
      ansible.builtin.shell: | 
        top -n 1 -b | head -n 8
      changed_when: false 
      register: top_output

    - name: Display top output
      ansible.builtin.debug:
        var: top_output.stdout_lines
