---
- name: Run NTPD status check
  hosts: "{{ host_name }}"
  gather_facts: no
  vars:
    sop_notes:
      - "NOTE: Ensure NTP is sychronised and offset is below 300 [Reference: KB0012165 ]"
      - "If ntp is 'sychronised' and offset is below 300, monitor for 20 mins. If alert persists, escalate to DO."
      - "If ntp is 'unsynchronised' and/or offset is above 300, restart ntpd as per KB above."
  tasks:
    - name: Display SOP Notes
      ansible.builtin.debug:
        msg: "{{ sop_notes }}"
          
    - name: Execute ntpstat to get status
      ansible.builtin.shell: ntpstat
      changed_when: false 
      register: ntpstat_output

    - name: Execute ntpq to get offset
      ansible.builtin.shell: ntpq -p
      changed_when: false 
      register: ntpq_output

    - name: Display ntpstat output
      ansible.builtin.debug:
        var: ntpstat_output.stdout_lines

    - name: Display ntpq output
      ansible.builtin.debug:
        var: ntpq_output.stdout_lines

