---
- name: Run CPU Usage check
  hosts: "{{ host_name }}"
  gather_facts: no
  tasks:
    - name: Execute top to get cpu usage
      ansible.builtin.shell: "top -n 1 -b | head -n 8"
      changed_when: false 
      register: top_output

    - name: Display top output
      ansible.builtin.debug:
        var: top_output.stdout_lines
