---
- name: Check Portnet Message Queue Depth
  hosts: "{{ host_name }}"
  become: true
  become_method: sudo
  become_user: sysadm
  gather_facts: no
  tasks:

    - name: Execute script to retrieve queue depth
      ansible.builtin.shell:
        cmd: echo {{ queue_name }} | /opt/sysadmin/gateway_scripts/tools/run_mqselfhelp.ksh liv dis_q_info
        executable: /bin/ksh
      changed_when: false
      register: queue_output

    - name: Display queue output
      ansible.builtin.debug:
        var: queue_output.stdout_lines
