---
- name: Check Portnet Message Queue Depth
  hosts: "{{ host_name }}"
  gather_facts: no
  tasks:
    - name: Execute script to retrieve queue depth
      ansible.builtin.shell: id
      become: true
      become_user: sysadm
      changed_when: false
      register: queue_output

    - name: Display queue output
      ansible.builtin.debug:
        var: queue_output.stdout_lines
