---
- name: Run nslcd/sssd check
  hosts: "{{ host_name }}"
  vars:
    sop_notes:
      - "NOTE: Check if LDAP is working by comparing both outputs [Reference: KB0012217 ]"
      - "1. 'getent passwd' ( which includes entries from LDAP if nslcd is working )"
      - "2. 'cat /etc/passwd' ( which includes only local user entries )"
      - "Differences between the two outputs indicate additional LDAP user entries, and that LDAP is working."
  tasks:
    - name: Display SOP Notes
      ansible.builtin.debug:
        msg: "{{ sop_notes }}"

    - name: Capture local passwd entries (from /etc/passwd)
      ansible.builtin.command:
        cmd: cat /etc/passwd
      changed_when: false
      register: local_passwd_output

    - name: Capture all passwd entries (from getent passwd)
      ansible.builtin.command:
        cmd: getent passwd
      changed_when: false
      register: getent_passwd_output

    - name: Extract additional LDAP entries
      ansible.builtin.shell:
        cmd: |
          echo "{{ getent_passwd_output.stdout_lines | difference(local_passwd_output.stdout_lines) | join('\n') }}"
      changed_when: false
      register: ldap_diff_output

    - name: Display additional LDAP entries (if any)
      ansible.builtin.debug:
        var: ldap_diff_output.stdout_lines

    - name: Display nslcd status
      ansible.builtin.debug:
        msg: "nslcd status: {{ ['ansible_facts']['services']['nslcd']['state'] | default('not found') }}"

    - name: Display sssd status
      ansible.builtin.debug:
        msg: "sssd status: {{ ['ansible_facts']['services']['sssd']['state'] | default('not found') }}"
