---
- name: Run NAMED service status check
  hosts: "{{ host_name }}"
  vars:
    sop_notes:
      - "NOTE: Check if DNS (Named) service is running [Reference: KB0011843 ]"
      - "This alert would normally be due to maintenance."
      - "If output below is empty, means DNS (Named) service is not up, immediately inform DO."
  tasks:
    - name: Display SOP Notes
      ansible.builtin.debug:
        msg: "{{ sop_notes }}"

    - name: Run command to check service
      ansible.builtin.shell: |
        ps -ef | grep named | grep -v grep
      changed_when: false
      register: named_output

    - name: Display named status output
      ansible.builtin.debug:
        var: named_output.stdout_lines
