---
- name: Run haproxy status check
  hosts: "{{ host_name }}"
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  vars:
    sop_notes:
      - "NOTE: Refer to latest logs and ensure status is UP [Reference: KB0011777 ]"
      - "If '<SERVICE> is DOWN' and '1 active server left', monitor for 30 mins for message '<SERVICE> is UP'. Else take action as per SOP."
      - "If '<SERVICE> is DOWN' and '0 active server left', take action as per SOP."
      - "If service is pc_imex_edo_bizfn -OR- pc_imex_soro, DO NOT wait 30 mins, take action as per SOP."
  tasks:
    - name: Display SOP Notes
      ansible.builtin.debug:
        msg: "{{ sop_notes }}"

    - name: Retrieve logs of Layer4
      ansible.builtin.shell: | 
        cat /var/log/messages | grep Layer4 | tail -n 10
      changed_when: false
      register: logs_output

    - name: Display logs output
      ansible.builtin.debug:
        var: logs_output.stdout_lines
