---
- name: Check Portnet Message Queue Depth
  hosts: "{{ host_name }}"
  vars:
    sop_notes:
      - "Refer to Consumers and queue depth [Reference: KB0011868 ]"
      - "If Consumers is 0, immediately escalate to DO"
      - "Else monitor for queue depth to decrease over time, no actions required"
      - "If queue depth keeps increasing, escalate to DO"
  tasks:
    - name: Display SOP Notes
      ansible.builtin.debug:
        msg: "{{ sop_notes }}"

    - name: Execute script to retrieve queue depth
      ansible.builtin.shell: "echo {{ queue_name }} | /opt/sysadmin/gateway_scripts/tools/run_mqselfhelp.ksh liv dis_q_info"
      become: true
      become_method: sudo
      become_user: sysadm
      changed_when: false
      register: queue_output

    - name: Display queue output
      ansible.builtin.debug:
        var: queue_output.stdout_lines
