---
- name: Retrieve Records from ServiceNow using ITSM module
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve configuration item info
      servicenow.itsm.configuration_item_info:
        instance: 
          host: "{{ sn_instance }}"
          user: "{{ sn_user }}"
          password: "{{ sn_password }}"
        name: "{{ survey_host_name }}"
      register: result

    - name: Display matching records
      debug:
        var: result
