---
- name: Retrieve Records from ServiceNow using ITSM module
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve configuration item info
      servicenow.itsm.configuration_item_info:
        instance: 
          host: "https://dev226839.service-now.com"
          username: "admin"
          password: "F*H8w0YkQ-ux"
        query:
          - name: = {{ survey_host_name }}
            sys_class_name: = cmdb_ci_linux_server
        return_fields:
          - ip_address
          - sys_id
      register: result

    - name: Display matching records
      debug:
        var: result.records.ip_address
