---
- name: Run task on dynamic host
  hosts: localhost
  gather_facts: no
  vars:
    host_name: "{{ survey_host_name }}"

  tasks:
    - name: Add the host dynamically
      add_host:
        name: "{{ host_name }}"
        groups: dynamic_group

- name: Run tasks on the dynamically added host
  hosts: dynamic_group
  gather_facts: no

  tasks:
    - name: Execute top to get cpu usage
      ansible.builtin.shell: | 
        top -n 1 -b | head -n 8
      changed_when: false 
      register: top_output

    - name: Display top output
      ansible.builtin.debug:
        var: top_output.stdout_lines
